name: Sync Branches

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Save master branch
      run: git checkout -b master_backup
    - uses: actions/checkout@master
      with:
        ref: ynab-importer
    - name: Merge master into ynab-import
      run: |
        git config user.email "bot@bcaldwell.ca"
        git config user.name "benjamin-bot"
        git merge master_backup
        git push origin HEAD:ynab-import
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ynab-importer
