name: Sync Branches

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Save master branch
      run: git checkout -b master
    - uses: actions/checkout@master
      with:
        ref: ynab-importer
    - name: Merge master into ynab-importer
      run: |
        git config user.email "bot@bcaldwell.ca"
        git config user.name "benjamin-bot"
        git merge master
        git push origin ynab-importer
